language: ruby
cache: bundler

jdk:
  - oraclejdk7

rvm:
  - 2.0.0
  - 2.1.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head
